# Generated by Django 6.0.5 on 2026-05-19 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['slug'], name='venue_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('room_number', models.PositiveIntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='venues.venue')),
            ],
            options={
                'ordering': ('venue__name', 'floor', 'name'),
                'indexes': [models.Index(fields=['venue', 'floor'], name='room_venue_floor_idx')],
                'constraints': [models.UniqueConstraint(fields=('venue', 'slug'), name='room_unique_slug_per_venue'), models.UniqueConstraint(fields=('venue', 'name'), name='room_unique_name_per_venue')],
            },
        ),
    ]
