# Generated by Django 6.0.5 on 2026-05-19 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprints', to='tracking.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='venues.room')),
            ],
            options={
                'ordering': ('-captured_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessPointSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(db_index=True, max_length=64)),
                ('bssid', models.CharField(blank=True, db_index=True, max_length=32)),
                ('signal', models.IntegerField(validators=[django.core.validators.MinValueValidator(-120), django.core.validators.MaxValueValidator(0)])),
                ('frequency', models.PositiveIntegerField(blank=True, null=True)),
                ('fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='tracking.fingerprint')),
            ],
            options={
                'ordering': ('-signal',),
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('predicted', 'Predicted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('raw_samples', models.JSONField(blank=True, default=list)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='tracking.device')),
                ('predicted_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_for', to='venues.room')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='venues.venue')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='fingerprint',
            index=models.Index(fields=['room', '-captured_at'], name='fp_room_captured_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspointsample',
            index=models.Index(fields=['ssid', 'bssid'], name='ap_ssid_bssid_idx'),
        ),
        migrations.AddConstraint(
            model_name='accesspointsample',
            constraint=models.UniqueConstraint(condition=models.Q(('bssid', ''), _negated=True), fields=('fingerprint', 'bssid'), name='ap_unique_bssid_per_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['venue', '-created_at'], name='scan_venue_created_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['device', '-created_at'], name='scan_device_created_idx'),
        ),
    ]
